import type { Metadata } from 'next';
import Link from 'next/link';
import { alternates } from '../../i18n';
import SiteHeader from '../../components/SiteHeader';
export const metadata: Metadata = { alternates:alternates('en','/confidentialite/'),title:'Privacy — Motion Wagram',robots:{index:false,follow:true} };
export default function Privacy() {
 return <><SiteHeader locale="en" /><main className="legal-page">
 <p className="section-label">MOTION WAGRAM</p><h1>Privacy</h1>
 <p className="legal-draft">Provisional information: retention periods and service configurations still need confirmation before public launch.</p>
 <section><h2>Your contact</h2><p>The data controller is MOTION WAGRAM SASU (SIREN 833 109 952). For questions about your data, contact Roman Chandler Fry at <a href="mailto:contact@motionwagram.com">contact@motionwagram.com</a>. Company details appear in the <Link href="/en/mentions-legales/">legal notice</Link>.</p></section>
 <section><h2>When you contact us</h2><p>The contact link opens your email application. The site has no contact form, user account or newsletter subscription. Emails you send may contain your name, email address, professional contact details, message and attachments.</p><p>We use this information to respond and, where appropriate, prepare a service. For project enquiries, the legal basis is taking pre-contractual steps at your request; for general enquiries, it is our legitimate interest in responding. You choose what to share; a reply address and relevant details are needed to answer.</p></section>
 <section><h2>Browsing and cookies</h2><p>The portfolio does not include advertising or analytics tools. Images and videos are served with the site without embedded YouTube or Vimeo players. If you select a language, the functional mw_locale cookie stores your preference for one year, and browser local storage keeps a copy until cleared. You can change it using FR / EN or clear it in your browser settings. On the root URL, without a saved choice, the country supplied by Cloudflare determines the language: French for France, English otherwise. Direct /fr or /en links are not redirected.</p><p>Cloudflare may process technical data, including IP address, connection time, requested URL and browser information, to deliver and secure the service. Providing and securing the site serves our legitimate interest in maintaining an available and protected service. Logs, any technical cookies and associated retention periods still need verification in our Cloudflare configuration. Any future trackers requiring consent must be blocked until consent is given.</p></section>
 <section><h2>Recipients and providers</h2><p>Messages are accessible to people authorised to handle your enquiry at Motion Wagram. Cloudflare, Inc., based in the United States, hosts and distributes the site. Its network may process data outside the European Economic Area. Its <a href="https://www.cloudflare.com/cloudflare-customer-dpa/">data processing agreement</a> describes safeguards, including standard contractual clauses for relevant transfers. Their application to our account and services remains to be checked. Business email uses OVHcloud and Outlook (Microsoft). Processing depends on the services and their configuration; Outlook may be used as a client for an OVHcloud-hosted mailbox. Any synchronisation with Microsoft services, processing locations and safeguards remain to be checked. See <a href="https://www.ovhcloud.com/en/personal-data-protection/">OVHcloud’s data protection information</a> and <a href="https://privacy.microsoft.com/en-us/privacystatement">Microsoft’s privacy statement</a>.</p></section>
 <section><h2>Retention</h2><p>Retention should cover the time necessary to handle enquiries and correspondence and, when a service is agreed, applicable legal retention and evidentiary requirements. Specific deletion periods for emails and technical logs remain to be defined and implemented; they are not yet confirmed in this version.</p></section>
 <section><h2>Your rights</h2><p>Under the conditions of the GDPR, you may request access, correction, deletion or restriction of processing. You also have a right to object, particularly to processing based on legitimate interests, and to data portability where applicable.</p><p>Send requests to <a href="mailto:contact@motionwagram.com">contact@motionwagram.com</a>. A response is generally required within one month; this may be extended by two months for complex or numerous requests, with notice during the first month. Additional information may be requested if there is reasonable doubt about your identity.</p><p>You may lodge a complaint with the <a href="https://www.cnil.fr/fr/adresser-une-plainte">CNIL</a>.</p></section>
 </main></>;
}
