import { alternates } from '../../i18n';
import type { Metadata } from 'next';
import Link from 'next/link';
import SiteHeader from '../../components/SiteHeader';
export const metadata: Metadata = { alternates: alternates('fr', '/confidentialite/'), title: 'Confidentialité — Motion Wagram', robots: { index: false, follow: true } };
export default function Privacy() {
  return <><SiteHeader locale="fr" /><main className="legal-page" lang="fr">
    <p className="section-label">MOTION WAGRAM</p><h1>Confidentialité</h1>
    <p className="legal-draft">Information provisoire : les durées de conservation et la configuration des services utilisés restent à confirmer avant la mise en ligne publique.</p>
    <section><h2>Votre point de contact</h2><p>Le responsable de traitement est la SASU MOTION WAGRAM (SIREN 833 109 952). Pour toute question concernant vos données, contactez-nous à l’attention de Roman Chandler Fry : <a href="mailto:contact@motionwagram.com">contact@motionwagram.com</a>. Les coordonnées de la société figurent dans les <Link href="/fr/mentions-legales/">mentions légales</Link>.</p></section>
    <section><h2>Lorsque vous nous contactez</h2><p>Le lien de contact ouvre votre application de messagerie. Le site ne comporte ni formulaire, ni compte utilisateur, ni inscription à une newsletter. Si vous envoyez un email, les données communiquées peuvent comprendre votre nom, votre adresse email, vos coordonnées professionnelles, le contenu du message et les pièces jointes.</p><p>Ces informations servent à répondre à votre demande et, le cas échéant, à préparer une prestation. La base juridique est l’exécution de mesures précontractuelles prises à votre demande lorsqu’il s’agit d’un projet de prestation ; pour une demande générale, elle est l’intérêt légitime à répondre aux sollicitations reçues. Vous choisissez les informations transmises ; une adresse de réponse et les éléments utiles à votre demande sont nécessaires pour vous répondre.</p></section>
    <section><h2>Navigation et cookies</h2><p>Le portfolio n’intègre pas d’outil publicitaire ou de mesure d’audience. Les images et vidéos sont servies avec le site, sans lecteur YouTube ou Vimeo intégré. Si vous choisissez une langue, le cookie fonctionnel mw_locale conserve ce choix pendant un an et le stockage local du navigateur en garde une copie jusqu’à son effacement. Vous pouvez modifier ce choix avec le sélecteur FR / EN ou l’effacer dans les paramètres du navigateur. À l’arrivée sur la racine du site, sans choix mémorisé, le pays fourni par Cloudflare détermine la langue : français pour la France, anglais sinon. Les liens directs vers /fr ou /en ne sont pas redirigés.</p><p>Cloudflare, notre hébergeur, peut traiter des données techniques, telles que l’adresse IP, la date de connexion, l’URL demandée et des informations sur le navigateur, pour fournir et sécuriser le service. La fourniture et la sécurisation du site répondent à notre intérêt légitime à maintenir un service disponible et protégé. Les journaux, éventuels cookies techniques et durées associés restent à vérifier dans la configuration Cloudflare utilisée. Tout ajout de traceurs soumis au consentement devra prévoir leur blocage avant votre accord.</p></section>
    <section><h2>Destinataires et prestataires</h2><p>Les échanges sont destinés aux personnes habilitées à traiter votre demande chez Motion Wagram. Cloudflare, Inc., établi aux États-Unis, assure l’hébergement et la distribution du site. Son réseau peut traiter des données hors de l’Espace économique européen. Son <a href="https://www.cloudflare.com/cloudflare-customer-dpa/">accord de traitement des données</a> décrit les garanties prévues, notamment les clauses contractuelles types pour les transferts concernés. Leur application au compte et aux services utilisés reste à vérifier. La messagerie professionnelle utilise OVHcloud et Outlook (Microsoft). Les conditions précises de traitement dépendent des services et de leur configuration : notamment, Outlook peut être utilisé comme logiciel de consultation d’une boîte hébergée chez OVHcloud. Les éventuelles synchronisations avec les services Microsoft, les lieux de traitement et les garanties applicables restent à vérifier. Consultez les informations de <a href="https://www.ovhcloud.com/fr/personal-data-protection/">OVHcloud sur la protection des données</a> et la <a href="https://privacy.microsoft.com/fr-fr/privacystatement">déclaration de confidentialité de Microsoft</a>.</p></section>
    <section><h2>Conservation</h2><p>Les critères à appliquer sont la durée nécessaire au traitement de la demande et au suivi des échanges, puis, lorsqu’une prestation est conclue, les obligations légales de conservation et les besoins de preuve applicables. Les délais précis de suppression des emails et des journaux techniques restent à définir et à mettre en œuvre ; ils ne sont pas encore confirmés dans cette version.</p></section>
    <section><h2>Vos droits</h2><p>Selon les conditions prévues par le RGPD, vous pouvez demander l’accès à vos données, leur rectification, leur effacement ou la limitation de leur traitement. Vous disposez également d’un droit d’opposition, notamment pour les traitements fondés sur l’intérêt légitime, et d’un droit à la portabilité lorsque ses conditions sont réunies.</p><p>Adressez votre demande à <a href="mailto:contact@motionwagram.com">contact@motionwagram.com</a>. Une réponse doit en principe être apportée sous un mois ; ce délai peut être prolongé de deux mois en cas de complexité ou de demandes nombreuses, avec information dans le premier mois. En cas de doute raisonnable sur votre identité, des informations complémentaires peuvent être demandées.</p><p>Vous pouvez introduire une réclamation auprès de la <a href="https://www.cnil.fr/fr/adresser-une-plainte">CNIL</a>.</p></section>
  </main></>;
}
